### ISSUE TITLE
Undefined _set_reset_password method call when executing the ForceChangePassword workflow

### ISSUE THREAD

**Issue by rub73** [pop-srw/streamlit-cognito-auth#12] opened 2024-02-20 10:34 UTC
When performing the first login after a user is created with a temporary password, the execution fails with an undefined method call in module/line auth.py::406,

`self._set_reset_password(username, password)`

The same module defines another function. `_set_reset_password_session`, at auth.py::428: replacing the former with the latter allows the execution to proceed with the changed password.

This is a blocking issue as it prevents any user with a temporary password to change it prior to logging in.

**Comment by parthamadhira** [comment] 2024-02-22 21:29
Ran in to the same issue

**Comment by dgallitelli** [comment] 2024-02-27 07:00
Same issue here

**Comment by hspoon-aws** [comment] 2024-02-28 15:49
Same here. seems the function _set_reset_password is missing due to typo. there is only _set_reset_password_session in the class

**Comment by EashanKaushik** [comment] 2024-03-07 22:05
same issue

**Comment by jbackofe** [comment] 2024-03-19 05:13
Same

**Comment by wei-m-teh** [comment] 2024-03-27 03:46
A temporary fix for this issue for me: Extend CognitoAuthenticator class and define _set_reset_password to look exactly like_set_reset_password_session:

class CognitoAuthenticator(streamlit_cognito_auth.CognitoAuthenticator):

    def _set_reset_password(self,
            reset_password_username: str, reset_password_password: str
        ) -> None:
            logger.info("Set password reset state")
            self.session_manager.set_reset_password_session(
                reset_password_username, reset_password_password
            )

**Comment by pop-srw** [comment] 2024-04-28 17:26
I'm so sorry for any inconvenience caused by this project. PR #10 should have solved the problem.

**Closed by pop-srw** 2024-04-28 17:26 UTC
